// Script to create a default author for blog posts
console.log('📝 Creating default author...')
console.log('')
console.log('To create a default author in Sanity Studio:')
console.log('1. Go to http://localhost:3000/studio')
console.log('2. Click on "Authors" in the left sidebar')
console.log('3. Click "Create new Author"')
console.log('4. Fill in the following information:')
console.log('')
console.log('   Name: miiyuh')
console.log('   Slug: miiyuh (auto-generated)')
console.log('   Bio: Creator of miiyuh.com - passionate about Attack on Titan, photography, and coding')
console.log('')
console.log('5. Add a profile image if desired')
console.log('6. Click "Publish"')
console.log('')
console.log('This author can then be assigned to blog posts!')
console.log('')
console.log('✅ Visit http://localhost:3000/studio to create your author profile')
